/* The site's sound identity. Every id maps to one file in /public/audio.
   Beds are seamless loops (the "room tone" of a section); oneshots are
   punctuation (a bell, a conch). Placeholder audio is generated by
   scripts/gen-audio-placeholders.mjs; replace each file with a real
   recording of the same name (see docs/AUDIO-BOOK.md). */

export type SoundKind = "bed" | "oneshot";
export type SoundDef = { id: string; src: string; kind: SoundKind; volume: number; loop?: boolean; note: string };

export const SOUNDS: Record<string, SoundDef> = {
  // ── beds (loops) ──────────────────────────────────────────────────────────
  "bed-base":      { id: "bed-base",      src: "/audio/drone-bed.wav",      kind: "bed", volume: 0.20, loop: true, note: "tanpura/shruti drone — the sacred room tone (hero, intro, default)" },
  "bed-sati":      { id: "bed-sati",      src: "/audio/sarangi-lament.wav", kind: "bed", volume: 0.26, loop: true, note: "mournful sarangi/bansuri — the Fall of Sati reel" },
  "bed-hingul":    { id: "bed-hingul",    src: "/audio/pakhawaj-build.wav", kind: "bed", volume: 0.24, loop: true, note: "pakhawaj that builds — the Hingul reel (penance to conquest)" },
  "bed-parshuram": { id: "bed-parshuram", src: "/audio/nagara-veer.wav",    kind: "bed", volume: 0.22, loop: true, note: "restrained nagara war-drums — the Parashurama reel" },
  "bed-crystal":   { id: "bed-crystal",   src: "/audio/drone-crystal.wav",  kind: "bed", volume: 0.16, loop: true, note: "high pure crystalline drone — the Brahmarandhra orb (crown chakra)" },
  "bed-finale":    { id: "bed-finale",    src: "/audio/resolve-note.wav",   kind: "bed", volume: 0.20, loop: true, note: "a single sustained resolving note — map + shrine finale, scene band" },
  "bed-grantha":   { id: "bed-grantha",   src: "/audio/drone-bed.wav",      kind: "bed", volume: 0.10, loop: true, note: "the faintest drone for the reading pages (reuses the base drone, very low)" },

  // ── oneshots (punctuation) ────────────────────────────────────────────────
  "cue-bell":   { id: "cue-bell",   src: "/audio/bell-ghanta.wav",  kind: "oneshot", volume: 0.50, note: "temple bell (ghanta) toll — the doors part, the shrine finale" },
  "cue-conch":  { id: "cue-conch",  src: "/audio/conch-shankh.wav", kind: "oneshot", volume: 0.45, note: "conch (shankh) blast — the door hero opening" },
  "cue-aakaar": { id: "cue-aakaar", src: "/audio/vocal-aakaar.wav", kind: "oneshot", volume: 0.30, note: "wordless female hum (aakaar) — the Devi's presence, used sparingly" },

  // ── micro-sounds (documented; not wired by default to avoid fatigue) ──────
  "ui-tick":   { id: "ui-tick",   src: "/audio/ghungroo-tick.wav", kind: "oneshot", volume: 0.20, note: "soft ghungroo tick — optional nav/UI micro-sound" },
  "ui-rustle": { id: "ui-rustle", src: "/audio/cloth-rustle.wav",  kind: "oneshot", volume: 0.25, note: "cloth rustle / page-turn — optional grantha page transitions" },

  // ── Tier 3 (supply a real recording; do NOT synthesize a mantra) ──────────
  "mantra":    { id: "mantra",    src: "/audio/mantra-hinglaj.wav", kind: "bed", volume: 0.18, loop: true, note: "the Hinglaj mantra, softly sung — shrine finale (Tier 3, real recording only)" },
};
